/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restoranku;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restoranku.Control_Masakan;

/**
 *
 * @author ASUS-AMD01
 */
public class Masakanku extends javax.swing.JDialog {
        Control_Masakan cm;
        String idmasakan,namamasakan,statusmakanan;
        int harga;
        DefaultTableModel dt;
    /**
     * Creates new form Masakanku
     */
    public Masakanku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cm = new Control_Masakan();
        tampildata();
        setobjek(false);
        btnbaru.setEnabled(true);
        btnupdate.setEnabled(false);
        btnsimpan.setEnabled(false);
        btnhapus.setEnabled(false);
        btnedit.setEnabled(false);
        btncanceledit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtidmasakan = new javax.swing.JTextField();
        txtnamamasakan = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        cbstatus = new javax.swing.JComboBox<>();
        btnhapus = new javax.swing.JButton();
        btncanceledit = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btnsimpan = new javax.swing.JButton();
        btnbaru = new javax.swing.JButton();
        btnedit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbmasakan = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtsearch = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("ID Masakan");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 69, -1, -1));

        jLabel3.setText("Nama Masakan");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 115, -1, -1));

        jLabel4.setText("Harga ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 161, -1, -1));

        jLabel5.setText(":");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 69, -1, -1));

        jLabel6.setText(":");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 115, -1, -1));

        jLabel7.setText(":");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 161, -1, -1));

        jLabel8.setText("Status Makanan");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel9.setText(":");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));
        jPanel1.add(txtidmasakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 62, 225, 35));
        jPanel1.add(txtnamamasakan, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 108, 225, 35));

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        jPanel1.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 153, 225, 35));

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Tersedia", "Kosong" }));
        jPanel1.add(cbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 140, 30));

        btnhapus.setText("Hapus");
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 90, -1));

        btncanceledit.setText("Cancel Edit");
        btncanceledit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncanceleditActionPerformed(evt);
            }
        });
        jPanel1.add(btncanceledit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 120, -1));

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 90, -1));

        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 90, -1));

        btnbaru.setText("Baru");
        btnbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbaruActionPerformed(evt);
            }
        });
        jPanel1.add(btnbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 80, -1));

        btnedit.setText("Edit");
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel1.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 410, -1));

        tbmasakan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Masakan", "Nama Masakan", "Harga", "Status"
            }
        ));
        tbmasakan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmasakanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbmasakan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 530, -1));

        jLabel10.setText("Search");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, -1, 30));

        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 130, -1));

        jLabel11.setText("| List Masakan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Input Menu Masakan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 930));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthargaActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
        simpandata();
        btnbaru.setEnabled(true);
        btnsimpan.setEnabled(true);
        btnhapus.setEnabled(false);
        btnupdate.setEnabled(false);
        btnedit.setEnabled(false);
        btncanceledit.setVisible(false);
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbaruActionPerformed
        // TODO add your handling code here:
        setobjek(true);
        baru();
        txtidmasakan.requestFocus();
        btnsimpan.setEnabled(true);
        btnupdate.setEnabled(false);
        btnedit.setEnabled(false);
        btnhapus.setEnabled(false);
        btnupdate.setEnabled(false);
        btncanceledit.setVisible(false);
    }//GEN-LAST:event_btnbaruActionPerformed

    private void tbmasakanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmasakanMouseClicked
        // TODO add your handling code here:
         setformtable();
        btnbaru.setEnabled(true);
        btnedit.setEnabled(true);
        btnhapus.setEnabled(true);
        btnupdate.setEnabled(false);
        btnsimpan.setEnabled(false);
        btncanceledit.setVisible(false);
    }//GEN-LAST:event_tbmasakanMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
         updatedata();
        btnupdate.setEnabled(true);
        btnedit.setEnabled(false);
        btnsimpan.setEnabled(false);
        btnhapus.setEnabled(false);
        btnbaru.setEnabled(true);
        btncanceledit.setVisible(false);
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
         setobjek(true);
        btnedit.setVisible(true);
        btnupdate.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnhapus.setEnabled(false);
        btnbaru.setEnabled(false);
        btncanceledit.setVisible(true);
        txtidmasakan.setEnabled(false);
    }//GEN-LAST:event_btneditActionPerformed

    private void btncanceleditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncanceleditActionPerformed
        // TODO add your handling code here:
        baru();
        btnbaru.setEnabled(true);
        btnupdate.setEnabled(false);
        btnsimpan.setEnabled(false);
        btnhapus.setEnabled(false);
        btnedit.setEnabled(false);
    }//GEN-LAST:event_btncanceleditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
           hapusdata();
        btnbaru.setEnabled(true);
        btnsimpan.setEnabled(false);
        btnhapus.setEnabled(false);
        btnupdate.setEnabled(false);
        btnedit.setEnabled(false);
        btncanceledit.setVisible(false);
    }//GEN-LAST:event_btnhapusActionPerformed

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
        // TODO add your handling code here:
        tampildata();
    }//GEN-LAST:event_txtsearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Masakanku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Masakanku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Masakanku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Masakanku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Masakanku dialog = new Masakanku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbaru;
    private javax.swing.JButton btncanceledit;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbmasakan;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtidmasakan;
    private javax.swing.JTextField txtnamamasakan;
    private javax.swing.JTextField txtsearch;
    // End of variables declaration//GEN-END:variables

private void simpandata() {
        idmasakan = txtidmasakan.getText();
        namamasakan = txtnamamasakan.getText();
        harga = Integer.parseInt(txtharga.getText());
        statusmakanan = (String) cbstatus.getSelectedItem();
        
        if (txtidmasakan.getText().isEmpty() || txtnamamasakan.getText().isEmpty() || txtharga.getText().isEmpty() || cbstatus.getSelectedIndex()== 0) {
          JOptionPane.showMessageDialog(rootPane,"data harus diisi","informasi",JOptionPane.INFORMATION_MESSAGE);
        } else {
         cm.setIdmasakan(idmasakan);
         cm.setNamamasakan(namamasakan);
         cm.setHarga(harga);
         cm.setStatusmasakan(statusmakanan);
         cm.simpandata();
        JOptionPane.showMessageDialog(rootPane,"Data berhasil disimpan","Informasi",JOptionPane.INFORMATION_MESSAGE);
        tampildata();
        baru();
        setobjek(false);
        
        }     
}

private void cari(){
     dt=(DefaultTableModel)tbmasakan.getModel();
     dt.setRowCount(0);
     cm.caridata(dt, txtsearch.getText().toString());
     tbmasakan.setModel(dt);
 }

private void tampildata () {
    DefaultTableModel dtm = (DefaultTableModel) tbmasakan.getModel();
    dtm.setRowCount(0);
    cm.tampildata(dtm);
    tbmasakan.setModel(dtm);
}


private void setformtable() {
     txtidmasakan.setText(tbmasakan.getValueAt(tbmasakan.getSelectedRow(), 0).toString());
     txtnamamasakan.setText(tbmasakan.getValueAt(tbmasakan.getSelectedRow(), 1).toString());
     txtharga.setText(tbmasakan.getValueAt(tbmasakan.getSelectedRow(), 2).toString());
     cbstatus.setSelectedItem(tbmasakan.getValueAt(tbmasakan.getSelectedRow(), 3).toString());
     
}

private void hapusdata() {
    idmasakan = txtidmasakan.getText();
    
    int conf = JOptionPane.showConfirmDialog(rootPane,"Apakah anda yakin akan menghapus data ini ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
    if (conf == 0) {
        cm.setIdmasakan(idmasakan);
        cm.hapusdata();
    JOptionPane.showMessageDialog(rootPane,"Data berhasil dihapus","Informasi",JOptionPane.INFORMATION_MESSAGE);
    tampildata();
    baru();
    setobjek(false);
    }
    
} 

private void updatedata() {
        idmasakan = txtidmasakan.getText();
        namamasakan = txtnamamasakan.getText();
        harga = Integer.parseInt(txtharga.getText());
        statusmakanan = (String) cbstatus.getSelectedItem();
        
        int conf = JOptionPane.showConfirmDialog(rootPane,"Apakah anda yakin akan mengubah data ini ?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (conf == 0) {
            cm.setIdmasakan(idmasakan);
            cm.setNamamasakan(namamasakan);
            cm.setHarga(harga);
            cm.setStatusmasakan(statusmakanan);
            cm.updatedata();
            tampildata();
            baru();
            setobjek(false);
        }
    }

private void baru() {
    txtidmasakan.setText(null);
    txtnamamasakan.setText(null);
    txtharga.setText(null);
    cbstatus.setSelectedIndex(0);
}

private void setobjek(boolean b) {
    txtidmasakan.setEnabled(b);
    txtnamamasakan.setEnabled(b);
    txtharga.setEnabled(b);
    cbstatus.setEnabled(b);
}
   


}
